### PR TITLE
add get_html_url method and attributes

### PR DESCRIPTION
**Pull request by Chayapol-c**

### CODE REVIEW

**Comment by nuttapol-kor** [comment]
Travis CI - build failed but it not failed because your file changed, so I approved.

**Review by nuttapol-kor — APPROVED** [review]
you just change from `subject = models.CharField(max_length=200)` 
to `subject = models.CharField(max_length=50)`
LGTM!

**Comment by nuttapol-kor** [comment]
Travis CI - build Failed. I think we forgot to **migrate** before start testing.

**Review by Bouncyyahomie — APPROVED** [review]
LGTM!

**Pull request merged**
