### PR TITLE
Improve nav and calendar.

### PR DESCRIPTION
**Pull request by Chayapol-c**
- Add the current page name in the navigation bar.
- Add an light unavailable button.
- overwrite bootstrap button styled for detail page (sorry I forgot that this branch is working on the homepage component).

If you guys think that it still has something missed please tell me.

### CODE REVIEW

**Comment by Chayapol-c** [comment]
I put form and meeting detail in a div tag, so conflicts occur.

**Review by nuttapol-kor — COMMENTED** [review]
Nice!! styling in base.html but it has conflict in `appointment/templates/appointment/detail.html`

**Comment by Chayapol-c** [comment]
Sorry, I resolve conflicts on this pr, so it becomes merging from master to improve-nav-and-calender. Then I decide to revert it back to before merging but it seems to revert back more than before.

**Comment by nuttapol-kor** [comment]
Has some conflicts and we can't fix yet so close this pr.

**Pull request closed without merging**
